### ISSUE TITLE
How to creat  *.node ,*.ele,and *.1.ploy file?

### ISSUE THREAD

**Issue by epi618** [ruboerner/FEMT2D#2]
### Sir,I modified your notebook code to create my mesh of model,but I do not know how to creat   *.node , *.ele, and *.1.ploy files,Please help me,thank a lot!

> mt.exportPLC(geom,
>              '../meshes/layered.poly', 
>              float_format='.8e')
> 
> print(geom)

> callTriangle('../meshes/layered.poly', 
>              quality=34.2,
>              verbose=False)

**Comment by ruboerner** [comment]
Have you installed the _triangle_ tool? Can you run it in a terminal window?

**Comment by epi618** [comment]
ok,I will try it,Thank you so much!
